Repository axondeepseg/axondeepseg, pull requests merged in 2021-04, with the labels that each got.

#487 Remove wildcard imports
  AxonDeepSeg/apply_model.py
  AxonDeepSeg/download_model.py
  AxonDeepSeg/download_tests.py
  AxonDeepSeg/integrity_test.py
  AxonDeepSeg/morphometrics/compute_morphometrics.py
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  AxonDeepSeg/network_construction.py
  AxonDeepSeg/segment.py
  AxonDeepSeg/testing/launch_performance_metrics.py
  AxonDeepSeg/testing/noise_simulation.py
  AxonDeepSeg/testing/statistics_generation.py
  AxonDeepSeg/train_network.py
  AxonDeepSeg/visualization/generate_axons_from_myelin.py
  notebooks/00-getting_started.ipynb
  notebooks/01-guide_dataset_building.ipynb
  notebooks/02-training_guideline.ipynb
  notebooks/03-performance_metrics.ipynb
  notebooks/04-morphometrics_extraction.ipynb
  test/data_management/test_dataset_building.py
  test/morphometrics/test_compute_morphometrics.py
  test/morphometrics/test_launch_morphometrics_computation.py
  test/test_ads_utils.py
  test/test_config_tools.py
  test/test_download_models.py
  test/test_download_tests.py
  test/test_segment.py
  test/testing/test_launch_performance_metrics.py
  test/testing/test_noise_simulation.py
  test/testing/test_segmentation_scoring.py
  test/testing/test_statistics_generation.py
  test/visualization/test_generate_axons_from_myelin.py
  test/visualization/test_get_masks.py
  test/visualization/test_merge_masks.py
  test/visualization/test_simulate_axons.py
  test/visualization/test_visualize.py
Labels: refactoring

#500 Add a reference to `Readme.md`
  README.md
Labels: readme

#491 Change the way the font is found in the postprocessing.py script
  AxonDeepSeg/postprocessing.py
Labels: fsleyes, testing

#434 Add CLI support to generate morphometrics file.
  .gitignore
  AxonDeepSeg/morphometrics/compute_morphometrics.py
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  docs/source/documentation.rst
  setup.py
  test/morphometrics/test_compute_morphometrics.py
  test/morphometrics/test_launch_morphometrics_computation.py
  test/test_segment.py
  test/visualization/test_visualize.py
Labels: feature, priority:HIGH

#493 Add tutorial video link in RTD
  docs/source/documentation.rst
Labels: documentation

#510 Fix black bar segmentation bug when width = height
  AxonDeepSeg/patch_management_tools.py
Labels: bug
