Repository axondeepseg/axondeepseg, pull requests merged in 2021-06, with the labels that each got.

#520 Add simulated image when `axon_shape` is circle
  test/morphometrics/test_compute_morphometrics.py
Labels: testing

#399 Implement Ellipse Minor Axis as Diameter
  AxonDeepSeg/morphometrics/compute_morphometrics.py
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  AxonDeepSeg/visualization/simulate_axons.py
  docs/source/documentation.rst
  notebooks/04-morphometrics_extraction.ipynb
  test/morphometrics/test_compute_morphometrics.py
  test/morphometrics/test_launch_morphometrics_computation.py
Labels: feature

#518 Implement Batch morphometrics for images present in directory/directories
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  config.py
  docs/source/documentation.rst
  test/morphometrics/test_launch_morphometrics_computation.py
Labels: cli, feature

#530 Add Optical Microscopy model in notebooks
  AxonDeepSeg/segment.py
  notebooks/00-getting_started.ipynb
  notebooks/02-training_guideline.ipynb
Labels: notebooks

#507 Refactor the code for the settings menu
  ads_plugin.py
Labels: fsleyes, refactoring

#533 Download models from Github repo
  AxonDeepSeg/download_model.py
Labels: models, refactoring

#534 Link the `test_files` to GitHub
  AxonDeepSeg/download_tests.py
Labels: refactoring, testing

#535 Small fix for `__test_files__` link
  AxonDeepSeg/download_tests.py
Labels: testing
