Repository axondeepseg/axondeepseg, pull requests merged in 2022-04, with the labels that each got.

#621 Add model repo links in the doc
  docs/source/documentation.rst
Labels: documentation

#625 Update ivadomed to 2.9.5
  environment.yml
Labels: installation

#622 Fix morphometrics bug when writing index/axonmyelin_index files
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  test/morphometrics/test_launch_morphometrics_computation.py
Labels: bug, exceptions, processing, cli

#630 Add test for 16bit TIF grayscale file
  test/test_segment.py
Labels: testing
