Repository axondeepseg/axondeepseg, pull requests merged in 2022-11, with the labels that each got.

#693 Update IVADOMED version
  environment.yml
Labels: installation

#694 Resolves warnings
  .gitignore
  AxonDeepSeg/ads_utils.py
  AxonDeepSeg/postprocessing.py
  environment.yml
  test/morphometrics/test_compute_morphometrics.py
  test/morphometrics/test_launch_morphometrics_computation.py
  test/test_ads_utils.py
  test/test_download_models.py
  test/test_download_tests.py
  test/test_integrity_test.py
  test/test_params.py
  test/test_postprocessing.py
  test/test_segment.py
  test/testing/test_launch_performance_metrics.py
  test/testing/test_noise_simulation.py
  test/testing/test_segmentation_scoring.py
  test/visualization/test_colorization.py
  test/visualization/test_generate_axons_from_myelin.py
  test/visualization/test_get_masks.py
  test/visualization/test_merge_masks.py
  test/visualization/test_simulate_axons.py
Labels: refactoring

#669 Improve and force imread/imwrite conversion to 8bit int
  AxonDeepSeg/ads_utils.py
  AxonDeepSeg/download_tests.py
  test/morphometrics/test_launch_morphometrics_computation.py
  test/test_ads_utils.py
Labels: processing, testing

#696 Segment images without patches
  AxonDeepSeg/apply_model.py
  AxonDeepSeg/segment.py
  AxonDeepSeg/zoom_factor_sweep.py
  docs/source/documentation.rst
  test/test_segment.py
Labels: feature
