Repository axondeepseg/axondeepseg, pull requests merged in 2023-01, with the labels that each got.

#708 Update ivadomed version to 2.9.8
  environment.yml
Labels: installation

#701 Add GPU ID setting in CLI and FSLeyes
  AxonDeepSeg/ads_utils.py
  AxonDeepSeg/apply_model.py
  AxonDeepSeg/integrity_test.py
  AxonDeepSeg/segment.py
  AxonDeepSeg/zoom_factor_sweep.py
  ads_plugin.py
  docs/source/documentation.rst
Labels: feature

#710 Fix 16 bit conversion bug
  AxonDeepSeg/ads_utils.py
Labels: bug

#713 remove openCV requirement
  environment.yml
Labels: installation
