Repository axondeepseg/axondeepseg, pull requests merged in 2024-12, with the labels that each got.

#845 Add CLI option to run all tests
  AxonDeepSeg/integrity_test.py
  docs/source/documentation.rst
  setup.py
Labels: testing

#846 Set `fail_on_warning = True` and resolve documentation warnings to ensure docs pass
  .readthedocs.yml
  docs/environment.yml
  docs/source/conf.py
  docs/source/documentation.rst
  docs/source/index.rst
  docs/source/requirements.txt
Labels: documentation

#848 Pin skimage<0.25
  requirements.txt
Labels: dependencies

#847 CLI: Log/print commit hash, and --version option
  AxonDeepSeg/__init__.py
  AxonDeepSeg/segment.py
  AxonDeepSeg/version.txt
  docs/source/requirements.txt
  install_ads
  install_ads.bat
  requirements.txt
  setup.py
Labels: cli

#844 Refactor config.py into ADS/params.py
  AxonDeepSeg/ads_utils.py
  AxonDeepSeg/apply_model.py
  AxonDeepSeg/integrity_test.py
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  AxonDeepSeg/params.py
  AxonDeepSeg/segment.py
  config.py
  plugins/napari_ADS/_widget.py
  test/morphometrics/test_compute_morphometrics.py
  test/morphometrics/test_launch_morphometrics_computation.py
  test/test_apply_model.py
  test/test_segment.py
  test/testing/test_launch_performance_metrics.py
  test/testing/test_segmentation_scoring.py
  test/visualization/test_merge_masks.py
Labels: refactoring

#850 Add Napari Plugin animation in doc
  docs/source/index.rst
Labels: documentation

#853 README: Add dark/light mode compatibility
  README.md
Labels: documentation
