Repository axondeepseg/axondeepseg, pull requests merged in 2025-02, with the labels that each got.

#876 Remove pygit2 & commit logging - breaks when ADS not downloaded as a git repo
  AxonDeepSeg/__init__.py
  AxonDeepSeg/segment.py
  AxonDeepSeg/version.txt
  CHANGELOG.md
Labels: bug, installation

#883 Make get_existing_models_list returns None when no models exist
  AxonDeepSeg/ads_utils.py
  test/test_ads_utils.py
  test/test_download_tests.py
Labels: bug

#868 Add click to delete "axon" objects and click to view morphometrics
  .github/workflows/run_tests.yaml
  AxonDeepSeg/morphometrics/compute_morphometrics.py
  docs/source/documentation.rst
  plugins/napari_ADS/_widget.py
  plugins/test/__init__.py
  plugins/test/test_widget.py
  requirements.txt
Labels: morphometrics, GUI

#887 Add checks to run download models if API called without having been downloaded during installation
  AxonDeepSeg/segment.py
  plugins/napari_ADS/_widget.py
Labels: installation

#884 Log current commit hash
  AxonDeepSeg/__init__.py
  AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
  AxonDeepSeg/segment.py
Labels: cli

#890 Update skimage and data-testing versions, update morphometrics pkl for consistency check
  AxonDeepSeg/download_tests.py
  pyproject.toml
Labels: testing, morphometrics

#889 Fix destination feature for download models/tests #885
  AxonDeepSeg/download_model.py
  AxonDeepSeg/download_tests.py
  pyproject.toml
  test/test_download_models.py
  test/test_download_tests.py
Labels: bug

#891 Move napari plugin into main package
  .github/workflows/run_tests.yaml
  AxonDeepSeg/ads_napari/Settings_menu_ui.ui
  AxonDeepSeg/ads_napari/__init__.py
  AxonDeepSeg/ads_napari/_widget.py
  AxonDeepSeg/ads_napari/napari.yaml
  AxonDeepSeg/ads_napari/settings_menu_ui.py
  install_ads
  install_ads.bat
  plugins/napari_ADS/napari.yaml
  plugins/pyproject.toml
  plugins/setup.cfg
  pyproject.toml
  test/ads_napari/__init__.py
  test/ads_napari/test_widget.py
Labels: installation, GUI
